### ISSUE TITLE
Add possibility to pass any Parse Server Option.

### ISSUE THREAD

**Issue by alexparfianovich** [bitnami/bitnami-docker-parse#50]
Add possibility to pass any Parse Server Option from the official list https://parseplatform.org/parse-server/api/master/ParseServerOptions.html so they will be added to config.json in the container.

Also please make it easy to use via Parse helm chart https://github.com/bitnami/charts/tree/master/upstreamed/parse

**Comment by rafariossaa** [comment]
Hi @alexparfianovich 
  I am adding your request to our backlog, meanwhile for the containers you can mount a local directory on `/bitnami`, for example modifying the docker compose file provided as follows:
```
...
  parse:
    image: 'bitnami/parse:3'
    ports:
      - '1337:1337'
    volumes:
      - './my_dir:/bitnami'
...
```
When you start the compose you will see the config.json file generated there and you will be able to change whatever you need and then restart the container.

For helm  you can proceed in a similar way.
