### ISSUE TITLE
Mapped Volumes with non-root permissions

### ISSUE THREAD

**Issue by dan-burt** [bitnami/bitnami-docker-parse#51]
**Description**

Running a local Docker CE instance, version 18.06.1-ce. I have created a Docker Compose file as indicated from the Github wiki/readme, with mapped volumes to allow for data persistence. I need to run this as "sudo docker-compose up -d" when in the current working directory.

```
version: '2'
services:
  mongodb:
    image: bitnami/mongodb:4.0
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - ./mongodb_data:/bitnami
  parse:
    image: bitnami/parse:3
    environment:
      - PARSE_ENABLE_CLOUD_CODE=yes
      - PARSE_SERVER_CLOUD="/opt/bitnami/parse/cloud/main.js"
    ports:
      - 1338:1337
    volumes:
      - ./parse_data:/bitnami
      - ./parse_cloud_code:/opt/bitnami/parse/cloud
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb

```

When I do this, Docker creates the stated folders on my behalf owned by "root". The MongoDB container stops with file permissions in the error log. If I pre-create these folders and grant 777 permissions from my own user account, the containers start.

I need a fully automated deployment. I hope to minimise any deviation from Bitnami's standard images and I am not wholly keen on generating my own images requiring subsequent management and upkeep.

In the Bitnami-parse Docker Compose file has the PUID and PGID environment variables set to 1000 in the MongoDB image, but it doesn't seem to have any effect.

**Steps to reproduce the issue:**

1. Create a base folder for the Bitnami-parse container
2. "cd" into the above folder
3. Create a docker-compose.yml file with the above configuration
4. Run "sudo docker-compose up -d"
5. Monitor container's status and log files & "ls -l" from within the working directory. For me, the sub-folders are owned by root user.

**Describe the results you received:**

Output of 1st container, MongoDB:

>  21:35:46.33 ,
>  21:35:46.33 Welcome to the Bitnami mongodb container,
>  21:35:46.34 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mongodb,
>  21:35:46.34 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mongodb/issues,
>  21:35:46.35 Send us your feedback at containers@bitnami.com,
>  21:35:46.35 ,
>  21:35:46.36 INFO  ==> ** Starting MongoDB setup **,
>  21:35:46.43 INFO  ==> Validating settings in MONGODB_* env vars...,
>  21:35:46.45 INFO  ==> Initializing MongoDB...,
>  21:35:46.49 INFO  ==> No injected configuration files found. Creating default config files...,
>  21:35:46.54 INFO  ==> Deploying MongoDB from scratch...,
> mkdir: cannot create directory '/bitnami/mongodb': Permission denied,

**Describe the results you expected:**

Running containers, with permissions of my own user account with UID = 1000

**Comment by miguelaeh** [comment]
Hi @dan-burt ,
This is probably a missconfiguration on the folders' permissions.
This is a non-root container, so, to mount local directories, you need to give the correct permissions for the user `1001` that will be the user executing the application.
You can find that information in the `README.md`: https://github.com/bitnami/bitnami-docker-parse#persisting-your-application, see the `NOTE` at the final of the section.

You need to create the derectories to mount and  use `chown` to change the owner user to `1001`.
Could you give a try to that and let us know what happens?

**Comment by dan-burt** [comment]
I can manually pre-provision the mapped host directories with "rwx" (777) permissions, and then run "sudo docker-compose up -d" and it works.

However, the execution of the docker-compose command & config needs to do this, with necessary permissions, i.e. fully automated from the standardised Bitnami images. Currently it seems to create it as root, even though the Dockerfile states "USER=1001", even though there is a mapped user on the host's /etc/passwd file:

`media:x:1001:1001::/home/media:`

Otherwise, there is supplemental configuration (i.e. creating this folder and permission structure) that needs to occur or a supplemental Docker image based upon Bitnami's, all of which would require supplemental management & maintenance.

I have also tried granting the container's parent folder full permissions and set the owner to the same 1001 (media) user as specified within the Dockerfile definition. This does NOT work either.

**Comment by miguelaeh** [comment]
Hi @dan-burt ,
That is probably because you are running `docker-compose` using `sudo`. The `docker-compose` tool creates the directories using the user that is executing itself.
If you want to create the directories automatically you could try to add a script before your `docker-compose` command to create (if they don't exists) and change the owner of the directories, and execute for example:
```
sh createdir.sh && docker-compose up
```

**Comment by dan-burt** [comment]
Created a docker group and added my user account to it (ala the post-install config documentation). Log out, then back in. Now I can run the docker commands (docker, docker-compose) as my (non-root) user.

However this Compose file still creates the bind / bound volumes as root:root, with 755 permissions.

What would the alternate config for this to use defined Named Volumes (hosted under the /var/lib/docker location and managed by Docker itself? I expect this may control the permissions within the container without having to open up the local host's directory structure permissions.

**Comment by dan-burt** [comment]
Creating a new container with the following docker-compose.yml file:

```
version: '2.4'
services:
  mongodb:
    image: bitnami/mongodb:4.0
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - vol_mongodb_data:/bitnami
  parse:
    image: bitnami/parse:3
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 1338:1337
    volumes:
      - vol_parse_data:/bitnami
      - vol_parse_cloud_data:/opt/bitnami/parse/cloud
    depends_on:
      - mongodb
    links:
      - mongodb:mongodb

volumes:
  vol_mongodb_data:
  vol_parse_data:
  vol_parse_cloud_data:
    external: true

networks:
  default:
    external:
      name: jingolan
```

This creates new Named Volumes (because they do not pre-exist and are created under the short syntax format), under the /var/lib/docker location. They are owned by root, but I do not get the MongoDB container's "permission denied" errors.

However, *within* the container these volumes are also mounted as root, if I access the container's console. Also I get a "I have no name!" for my username, and I am unable to perform "sudo" commands inside the container.

Checking both container's /etc/passwd:
- MongoDB container has no UID of 1000 or 1001. Presume the ENV VARs supplied are not doing anything!
- Parse container has a user name "bitnami" for UID 1000

The Docker host has:
- UID 1000 = main SSH user account
- UID 1001 = media

However, permissions are not being set by any of these in either container.

Another broken component is the Cloud Code functionality. If I provide the 2 required environment variables (PARSE_ENABLE_CLOUD_CODE & PARSE_SERVER_CLOUD), I guess it needs to be able to find the /opt/bitnami/parse/cloud/main.js file I specify for the 2nd parameter. This causes the container to STOP but as I cannot manually "sudo touch", I cannot manually create this to test. 

There is no default "main.js" file for the Cloud Code purpose within the Parse container. I suggest there should be, wherever Bitnami decide, to stop the auto-STOP behaviour if the file doesn't exist.

Ultimately though, the permissions do not seem to be being applied as expected.
