### ISSUE TITLE
mongodb environment

### ISSUE THREAD

**Issue by farzadi** [bitnami/bitnami-docker-parse#55]
Hi, is there any way to add username and password to MongoDB 
I try this by adding these lines to environment part inside docker-compose.yml

```
 mongodb:
    image: 'docker.io/bitnami/mongodb:4.2-debian-10'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - 'mongodb_data:/bitnami'
```
but how can I connect parse to mongo now?

**Comment by juan131** [comment]
Hi @farzadi 

As it's explained in the MongoDB container, you can create a custom user/password/database during MongoDB initialization. Check the link below for more information: 

- https://github.com/bitnami/bitnami-docker-mongodb#creating-a-user-and-database-on-first-run

Please note that you have to indicate the `MONGODB_USER` and `MONGODB_PASSWORD` also in the Parse container, so it knows the credentials to use to connect to the MongoDB server.

**Comment by farzadi** [comment]
I did what you said but now parse-dashboard is blank. I think they cant connect to each other now.is this correct?

```
version: '2'
services:
  mongodb:
    image: 'docker.io/bitnami/mongodb:4.2-debian-10'
    environment:
      - MONGODB_USERNAME=my_user
      - MONGODB_PASSWORD=password123
    volumes:
      - 'mongodb_data:/bitnami'
  parse:
    image: 'docker.io/bitnami/parse:4-debian-10'
    environment:
      - PARSE_APP_ID=xxxx
      - PARSE_REST_API_KEY=xxxx
      - PARSE_MASTER_KEY=xxxx
      - MONGODB_USER=my_user
      - MONGODB_PASSWORD=password123
    ports:
      - '1337:1337'
    volumes:
      - 'parse_data:/bitnami'
    depends_on:
      - mongodb
  parse-dashboard:
    image: 'docker.io/bitnami/parse-dashboard:2-debian-10'
    environment:
      - PARSE_DASHBOARD_USER=xxxx
      - PARSE_DASHBOARD_PASSWORD=xxxx
      - PARSE_DASHBOARD_APP_NAME=xxxx
      - PARSE_APP_ID=xxxx
      - PARSE_MASTER_KEY=xxxx
    ports:
      - '4040:4040'
    volumes:
      - 'parse_dashboard_data:/bitnami'
    depends_on:
      - parse
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
```

**Comment by juan131** [comment]
Hi @farzadi 

Could you try with the Docker Compose below?

```yaml
version: '2'
services:
  mongodb:
    image: 'docker.io/bitnami/mongodb:4.2-debian-10'
    environment:
      - MONGODB_ROOT_PASSWORD=password123
    volumes:
      - 'mongodb_data:/bitnami'
  parse:
    image: 'docker.io/bitnami/parse:4-debian-10'
    environment:
      - PARSE_APP_ID=someid
      - PARSE_MASTER_KEY=somemasterkey
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=root
      - MONGODB_PASSWORD=password123
    ports:
      - '1337:1337'
    volumes:
      - 'parse_data:/bitnami'
    depends_on:
      - mongodb
  parse-dashboard:
    image: 'docker.io/bitnami/parse-dashboard:2-debian-10'
    environment:
      - PARSE_DASHBOARD_USER=user
      - PARSE_DASHBOARD_PASSWORD=password
      - PARSE_DASHBOARD_APP_NAME=foo
      - PARSE_HOST=127.0.0.1
      - PARSE_USE_HOSTNAME=yes
      - PARSE_PORT_NUMBER=1337
      - PARSE_APP_ID=someid
      - PARSE_MASTER_KEY=somemasterkey
    ports:
      - '4040:4040'
    volumes:
      - 'parse_dashboard_data:/bitnami'
    depends_on:
      - parse
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
  parse_dashboard_data:
    driver: local
```

Some explanations:

1. Parse needs the root credentials of MongoDB since it creates its own databases during the initialization there.
2. The dashboard is configured with `PARSE_HOST=127.0.0.1` since I'm accessing the dashboard with my browser through localhost. The reason is that env. variable should be set with a hostname/IP that's accessible from the browser you're using to access the Dashboard.
